FROM openjdk:8-jdk-alpine
MAINTAINER com.berkay.yelken
COPY target/autonomous_car_park-1.0.0-final.jar autonomous_car_park-1.0.0-final.jar
ENTRYPOINT ["java","-jar","/autonomous_car_park-1.0.0-final.jar"]